routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/webpack', function () {
    return view('webpack_test');
});

Route::get('robots.txt', 'RobotsTxtController');

Route::get('/hub/{hub}/{top?}', 'HubController@show')->name('hub');

Route::get('/post/{post}', 'PostController@show')->name('post');
Route::post('/post/{post}/vote', 'PostController@vote');

app/Models/Bookmark.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bookmark extends Model
{
    //
}

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
}

app/Models/Hub.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Hub extends Model
{
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function resolveRouteBinding($value)
    {
        return $this->where('slug', $value)->firstOrFail();
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Models/Mark.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    //
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model
{
    const TOP_PREFIX = 'top';

    public function getRouteKeyName()
    {
        return 'post';
    }

    public function resolveRouteBinding($value)
    {
        return $this->findOrFail($value);
    }

    public function scopeTop($query, $top)
    {
        if ($top && Str::startsWith($top, self::TOP_PREFIX)) {
            $rating = (int) Str::substr($top, strlen(self::TOP_PREFIX));
            return $query->where('rating', '>=', $rating);
        }

        return $query;
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function hubs()
    {
        return $this->belongsToMany(hub::class);
    }

    public function marks()
    {
        return $this->belongsToMany(Mark::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function bookmarks()
    {
        return $this->hasMany(Bookmark::class);
    }

    public function votes()
    {
        return $this->hasMany(Vote::class);
    }

    public function positiveVotes()
    {
        return $this->votes()->where('value', 1);
    }

    public function negativeVotes()
    {
        return $this->votes()->where('value', -1);
    }

    public function getPreviewAttribute()
    {
        return implode('. ', array_slice(explode('. ', $this->content), 0, 7));
    }

    public function getCreatedDateAttribute()
    {
        if ($this->created_at->isToday()) {
            return $this->created_at->translatedFormat('сегодня в H:i');
        } else if ($this->created_at->isYesterday()) {
            return $this->created_at->translatedFormat('вчера в H:i');
        } else {
            return $this->created_at->translatedFormat('j F Y в H:i');
        }
    }

    public function getPositiveVotes() {
        return $this->votes->filter(function ($vote, $key){
                return $vote->value === 1;
            });
    }

    public function getNegativeVotes() {
        return $this->votes->filter(function ($vote, $key){
                return $vote->value === -1;
            });
    }

    public function alreadyVotedByUser($userVotes) {
        foreach ($userVotes as $userVote) {
            $postVote = $this->votes->first(function ($postVote, $key) use ($userVote) {
                return $postVote->id === $userVote;
            });

            if ($postVote) {
                return true;
            }
        }
        return false;
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nickname', 'email', 'full_name', 'avatar'
    ];
}

app/Models/Vote.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Vote extends Model
{
    protected $fillable = ['value'];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/helpers.php
<?php

function in_production()
{
    return app()->environment('production');
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HubController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hub;
use App\Models\Post;

class HubController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param Hub  $hub
     * @param string $top
     * @return \Illuminate\Http\Response
     */
    public function show(Hub $hub, string $top = null)
    {
        $posts = Post::whereHas('hubs', fn($query) => $query->where('hubs.id', $hub->id))
            ->top($top)
            ->with([
                'author',
                'hubs',
                'marks'
            ])
            ->withCount([
                'comments',
                'bookmarks',
                'votes',
                'positiveVotes',
                'negativeVotes'
            ])
            ->paginate(10);

        return response()->view('hub.index', compact('hub', 'posts', 'top'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Vote;

class PostController extends Controller
{
    /**
     * Return page with post by id
     *
     * @param  Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $post->load([
                'author',
                'hubs',
                'marks',
                'votes'
            ])->loadCount([
                'comments',
                'bookmarks'
            ]);

        return response()->view('post.index', [ 'post' => $post ]);
    }

    /**
     * Add vote to the post
     *
     * @param Post $post
     * @return \Illuminate\Http\Response
     */
    public function vote(Post $post)
    {
        $post = \DB::transaction(function () use ($post) {
            $newVoteValue = request()->input('data.value');
            $userVotes = request()->session()->get('votes', []);

            if ($post->alreadyVotedByUser($userVotes)) {
                abort(403, 'Post already voted');
            }

            $newVote = $post->votes()->save(new Vote([ 'value' => $newVoteValue ]));
            $post->increment('rating', $newVoteValue);

            request()->session()->push('votes', $newVote->id);

            $post->loadCount(['positiveVotes', 'negativeVotes']);

            return $post;
        });

        return response()->json([
            'positiveVotesCount' => $post->positive_votes_count,
            'negativeVotesCount' => $post->negative_votes_count
        ]);
    }
}

app/Http/Controllers/RobotsTxtController.php
<?php

namespace App\Http\Controllers;

class RobotsTxtController extends Controller
{
    public function __invoke()
    {
        $env = app()->environment();
        $view = "robotstxt.{$env}";
        $view = view()->exists($view) ? $view : "robotstxt.dev";

        $response = response()->view($view)->header('Content-Type', 'text/plain');
        $response->header('Content-Length', mb_strlen($response->getOriginalContent()));

        return $response;
    }
}

resources/views/hub/header.blade.php
<div class="layout__cell layout__cell_body">
    <div class="page-header page-header_full" id="hub_{{ $hub->id }}">
        <div class="page-header_wrapper">
            <div class="media-obj media-obj_page-header">
                <a href="{{ route('hub', [ 'hub' => $hub->slug ]) }}" class="media-obj__image">
                    <img src="{{ $hub->image }}" width="48" height="48" class="media-obj__image-pic">
                </a>
                <div class="media-obj__body media-obj__body_page-header media-obj__body_page-header_hub">
                <div class="page-header__stats">
                    <div class="page-header__stats-value">111,92</div>
                    <div class="page-header__stats-label">Рейтинг</div>
                </div>
            </div>
        </div>
    </div>

    <div class="page-header__info">
        <h1 class="page-header__info-title">{{ $hub->title }}</h1>
        <span class="n-profiled_hub" title="Профильный хаб"></span>
        <h2 class="page-header__info-desc">{{ $hub->description }}</h2>
    </div>
</div>

resources/views/hub/index.blade.php
@extends('layouts.main')

@section('content')
<div class="layout__row layout__row_body">
    @include('hub.header')

    <div class="column-wrapper column-wrapper_tabs js-sticky-wrapper">
        <div class="content_left js-content_left">
            @include('hub.tabs')

            <div class="posts_list">
                @include('hub.posts')
                <div class="page__footer">
                    {{ $posts->links('hub.pagination') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/hub/posts.blade.php
<ul class="content-list shortcuts_items">
    @foreach ($posts as $post)
    <li class="content-list__item content-list__item_post shortcuts_item" id="post_{{ $post->id }}">
        <article class="post post_preview" lang="ru">

            <header class="post__meta">
                <a href="{{ $post->author->nickname }}" class="post__user-info user-info" title="Автор публикации">
                    <img src="{{ $post->author->avatar }}" width="24" height="24" class="user-info__image-pic user-info__image-pic_small">
                    <span class="user-info__nickname user-info__nickname_small">{{ $post->author->nickname }}</span>
                </a>
                <span class="post__time">{{ $post->created_date }}</span>
            </header>

            <h2 class="post__title">
                <a href="{{ route('post', [ 'post' => $post->id ]) }}" class="post__title_link">{{ $post->title }}</a>
            </h2>

            <ul class="post__hubs inline-list">
                @foreach ($post->hubs as $hub)
                <li class="inline-list__item inline-list__item_hub">
                    <a href="{{ route('hub', [ 'hub' => $hub->slug ]) }}"
                        class="inline-list__item-link hub-link "
                        rel="nofollow">
                        {{ $hub->title }},
                    </a>
                </li>
                @endforeach
            </ul>

            <ul class="post__marks inline-list">
                @foreach ($post->marks as $mark)
                <li class="inline-list__item inline-list__item_post-type">
                    <a href="#" class="post__type-label" title="Перейти в песочницу">{{ $mark->title }}</a>
                </li>
                @endforeach
            </ul>

            <div class="post__body post__body_crop ">

                <div class="post__text post__text-html  post__text_v1 ">
                    {{ $post->preview }}
                </div>

                <a class="btn btn_x-large btn_outline_blue post__habracut-btn" href="{{ route('post', [ 'post' => $post->id ]) }}/#habracut">Читать дальше →</a>
            </div>

            <footer class="post__footer">
                <ul class="post-stats  js-user_" data-post-type="publish_ugc_ru,h_91,h_260,h_359,f_develop" id="infopanel_post_{{ $post->id }}">

                    <li class="post-stats__item">
                        <div class="post-stats__result">
                            <span class="post-stats__result-icon">
                                <svg class="icon-svg_votes" width="10" height="16">
                                    <use xlink:href="/images/svg/common-svg-sprite.svg#counter-rating"></use>
                                </svg>
                            </span>
                            <span class="post-stats__result-counter voting-wjt__counter_{{ $post->rating >= 0 ? 'positive' : 'negative' }}"
                                title="Всего голосов {{ $post->votes_count }}: ↑{{ $post->positive_votes_count }} и ↓{{ $post->negative_votes_count }}">
                                {{ $post->rating }}
                            </span>
                        </div>
                    </li>

                    <li class="post-stats__item post-stats__item_bookmark">
                        <button type="button" class="btn bookmark-btn bookmark-btn_post " data-post-type="publish_ugc_ru,h_91,h_260,h_359,f_develop" data-type="2" data-id="{{ $post->id }}" data-action="add" title="Только зарегистрированные пользователи могут добавлять публикации в закладки" disabled="">
                            <span class="btn_inner">
                                <svg class="icon-svg_bookmark" width="10" height="16">
                                    <use xlink:href="/images/svg/common-svg-sprite.svg#book"></use>
                                </svg>
                                <span class="bookmark__counter js-favs_count" title="Количество пользователей, добавивших публикацию в закладки">
                                    {{ $post->bookmarks_count }}
                                </span>
                            </span>
                        </button>
                    </li>

                    <li class="post-stats__item post-stats__item_views">
                        <div class="post-stats__views" title="Количество просмотров">
                            <svg class="icon-svg_views-count" width="21" height="12">
                                <use xlink:href="/images/svg/common-svg-sprite.svg#eye"></use>
                            </svg>
                            <span class="post-stats__views-count">
                                {{ $post->views }}
                            </span>
                        </div>
                    </li>

                    <li class="post-stats__item post-stats__item_comments">
                        <a href="{{ route('post', [ 'post' => $post->id ]) }}/#comments" class="post-stats__comments-link" rel="nofollow">
                            <svg class="icon-svg_post-comments" width="16" height="16">
                                <use xlink:href="/images/svg/common-svg-sprite.svg#comment"></use>
                            </svg>
                            <span class="post-stats__comments-count" title="Читать комментарии">
                                {{ $post->comments_count }}
                            </span>
                        </a>
                    </li>

                </ul>
            </footer>
        </article>
    </li>
    @endforeach
</ul>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="lang" content="{{ app()->getLocale() }}">
    <title>{{ config('app.name') }} - @yield('title')</title>

    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>
<body class="nl">
    <div id="app">
        @include('shared.services')
        @include('shared.navigation')

        @yield('content')

        @include('shared.footer-links')
        @include('shared.footer')
    </div>

<script defer src="{{ mix('js/manifest.js') }}"></script>
<script defer src="{{ mix('js/vendor.js') }}"></script>
<script defer src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/post/index.blade.php
@extends('layouts.main')

@section('content')
<div class="layout__cell layout__cell_body">
    <section class="column-wrapper column-wrapper_post js-sticky-wrapper">
        <div class="content_left js-content_left">
            <article class="post post_full" id="post_{{ $post->id }}" lang="ru">
                <div class="post__wrapper">
                    <header class="post__meta">
                        <a href="#" class="post__user-info user-info" title="Автор публикации">
                            <img src="{{ $post->author->avatar }}" width="24" height="24" class="user-info__image-pic user-info__image-pic_small">
                            <span class="user-info__nickname user-info__nickname_small">{{ $post->author->nickname }}</span>
                        </a>
                        <span class="post__time" data-time_published="{{ $post->created_at }}">{{ $post->created_date }}</span>
                    </header>

                    <h1 class="post__title post__title_full">
                        <span class="post__title-text">{{ $post->title }}</span>
                    </h1>

                    <ul class="post__hubs post__hubs_full-post inline-list">
                        @foreach ($post->hubs as $hub)
                        <li class="inline-list__item inline-list__item_hub">
                            <a href="{{ route('hub', [ 'hub' => $hub->slug ]) }}"
                                class="inline-list__item-link hub-link "
                                rel="nofollow"
                                title="Вы не подписаны на этот хаб">
                                {{ $hub->title }},
                            </a>
                        </li>
                        @endforeach
                    </ul>

                    <ul class="post__marks inline-list">
                        @foreach ($post->marks as $mark)
                        <li class="inline-list__item inline-list__item_post-type">
                            <a href="#" class="post__type-label" title="Перейти в песочницу">{{ $mark->title }}</a>
                        </li>
                        @endforeach
                    </ul>

                    <div class="post__body post__body_full">
                        <div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="{{ route('post', [ 'post' => $post->id ]) }}">
                            {{ $post->content }}
                        </div>
                    </div>

                    <dl class="post__tags">
                        <dt class="post__tags-label">Теги:</dt>
                        <dd class="post__tags-list">
                            <ul class="inline-list inline-list_fav-tags js-post-tags">
                                @foreach ($post->tags as $tag)
                                <li class="inline-list__item inline-list__item_tag">
                                    <a href="#" rel="tag" class="inline-list__item-link post__tag  ">
                                        {{ $tag->title }}
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </dd>
                    </dl>

                    <dl class="post__tags">
                        <dt class="post__tags-label">Хабы:</dt>
                        <dd class="post__tags-list">
                            <ul class="inline-list inline-list_fav-tags js-post-hubs">
                                @foreach ($post->hubs as $hub)
                                <li class="inline-list__item inline-list__item_tag">
                                    <a href="{{ route('hub', [ 'hub' => $hub->slug ]) }}" rel="tag" class="inline-list__item-link post__tag  ">
                                        {{ $hub->title }}
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </dd>
                    </dl>
                </div>
            </article>
        </div>
    </section>

    <section class="column-wrapper column-wrapper_post-additionals">
        <div class="content_left">
            <div class="post-additionals">
                <ul class="post-stats post-stats_post js-user_" data-post-type="publish_ugc_ru,h_91,h_17110,f_develop" id="infopanel_post_{{ $post->id }}">
                    <li class="post-stats__item post-stats__item_voting-wjt">
                        <post-votes
                            :post-id="{{ $post->id }}"
                            :already-voted="{{ $post->alreadyVotedByUser(session('votes', [])) ? 'true' : 'false' }}"
                            :positive-votes="{{ $post->getPositiveVotes()->count() }}"
                            :negative-votes="{{ $post->getNegativeVotes()->count() }}">
                        </post-votes>
                    </li>

                    <li class="post-stats__item post-stats__item_bookmark">
                        <button type="button" class="btn bookmark-btn bookmark-btn_post " data-post-type="publish_ugc_ru,h_91,h_17110,f_develop" data-type="2" data-id="{{ $post->id }}" data-action="add" title="Только зарегистрированные пользователи могут добавлять публикации в закладки" onclick="posts_add_to_favorite(this);" disabled="">
                            <span class="btn_inner">
                                <svg class="icon-svg_bookmark" width="10" height="16">
                                    <use xlink:href="/images/svg/common-svg-sprite.svg#book"></use>
                                </svg>
                                <span class="bookmark__counter js-favs_count" title="Количество пользователей, добавивших публикацию в закладки">
                                    {{ $post->bookmarks_count }}
                                </span>
                            </span>
                        </button>
                    </li>

                    <li class="post-stats__item post-stats__item_views">
                        <div class="post-stats__views" title="Количество просмотров">
                            <svg class="icon-svg_views-count" width="21" height="12">
                                <use xlink:href="/images/svg/common-svg-sprite.svg#eye"></use>
                            </svg>
                            <span class="post-stats__views-count">
                                {{ $post->views }}
                            </span>
                        </div>
                    </li>

                    <li class="post-stats__item post-stats__item_comments">
                        <a href="{{ route('post', [ 'post' => $post->id ]) }}/#comments" class="post-stats__comments-link" rel="nofollow">
                            <svg class="icon-svg_post-comments" width="16" height="16">
                                <use xlink:href="/images/svg/common-svg-sprite.svg#comment"></use>
                            </svg>
                            <span class="post-stats__comments-count" title="Читать комментарии">
                                {{ $post->comments_count }}
                            </span>
                        </a>
                    </li>

                    <li class="post-stats__item post-stats__item_share">
                        <div class="dropdown dropdown_share">
                            <div href="{{ route('post', [ 'post' => $post->id ]) }}/#comments" data-toggle="dropdown" class="post-stats__share" rel="nofollow" tabindex="0">
                                <svg class="icon-svg_post-share" width="24" height="24">
                                    <use xlink:href="/images/svg/common-svg-sprite.svg#share"></use>
                                </svg>
                                <span class="post-stats__comments-text" title="Поделиться">
                                    Поделиться
                                </span>
                            </div>
                            <div class="dropdown-container">
                                <div class="post-share">
                                    <ul class="post-share__buttons">
                                        <li class="post-share__item post-share__item_post">
                                            <span class="post-share__item-link post-share__item-link_normal post-share__item-link_copy" title="Скопировать ссылку" onclick="copyCurrentUrl(), $('.dropdown_share').removeClass('dropdown_active')">
                                                Скопировать ссылку
                                            </span>
                                        </li>
                                        <li class="post-share__item post-share__item_post">
                                            <a href="https://www.facebook.com/sharer/sharer.php?u=https://habr.com/ru/post/{{ $post->id }}/" class="post-share__item-link post-share__item-link_normal post-share__item-link_facebook" title="Facebook" onclick="window.open(this.href, 'Facebook', 'width=640,height=436,toolbar=0,status=0'); return false">
                                                Facebook
                                            </a>
                                        </li>
                                        <li class="post-share__item post-share__item_post">
                                            <a href="https://twitter.com/intent/tweet?text=5+%D0%BF%D1%80%D0%B5%D1%82%D0%B5%D0%BD%D0%B7%D0%B8%D0%B9+%D0%BA+Deno+https://habr.com/p/{{ $post->id }}/+via+%40habr_com" class="post-share__item-link post-share__item-link_normal post-share__item-link_twitter" title="Twitter" onclick="window.open(this.href, 'Twitter', 'width=800,height=300,resizable=yes,toolbar=0,status=0'); return false">
                                                Twitter
                                            </a>
                                        </li>
                                        <li class="post-share__item post-share__item_post">
                                            <a href="https://vk.com/share.php?url=https://habr.com/ru/post/{{ $post->id }}/" class="post-share__item-link post-share__item-link_normal post-share__item-link_vkontakte" title="ВКонтакте" onclick="window.open(this.href, 'ВКонтакте', 'width=800,height=300,toolbar=0,status=0'); return false">
                                                ВКонтакте
                                            </a>
                                        </li>
                                        <li class="post-share__item post-share__item_post">
                                            <a href="https://t.me/share/url?url=https://habr.com/ru/post/504964/&amp;title=5 претензий к Deno" class="post-share__item-link post-share__item-link_normal post-share__item-link_telegram" title="Telegram" onclick="window.open(this.href, 'Telegram', 'width=800,height=300,toolbar=0,status=0'); return false">
                                                Telegram
                                            </a>
                                        </li>
                                        <li class="post-share__item post-share__item_post">
                                            <a href="https://getpocket.com/edit?url=https://habr.com/ru/post/504964/&amp;title=5 претензий к Deno" class="post-share__item-link post-share__item-link_normal post-share__item-link_pocket" title="Pocket" target="_blank" rel=" noopener">
                                                Pocket
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>

                <div class="author-panel author-panel_user">
                    <div class="author-panel__user-info">
                        <div class="user-info" data-user-login="${{ $post->author->nickname }}">
                            <a href="#" class="media-obj__image">
                                <img src="{{ $post->author->avatar }}" width="48" height="48" class="media-obj__image-pic media-obj__image-pic_user">
                            </a>

                            <div class="user-info__about">
                                <div class="user-info__links">
                                    <a href="#" class="user-info__nickname user-info__nickname_doggy">
                                        {{ $post->author->nickname }}
                                    </a>
                                </div>
                            <div class="user-info__specialization">JavaScript разработчик</div>
                        </div>
                    </div>
                </div>

                <ul class="user-info__contacts inline-list">
                    <li class="inline-list__item inline-list__item_contact-link"><a href="https://qna.habr.com/user/{{ $post->author->nickname }}">Хабр Q&amp;A</a></li>
                    <li class="inline-list__item inline-list__item_contact-link"><a href="https://github.com/{{ $post->author->nickname }}/">Github</a></li>
                    <li class="inline-list__item inline-list__item_contact-link"><a href="https://telegram.me/{{ $post->author->nickname }}">Telegram</a></li>
                </ul>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/robotstxt/dev.blade.php
User-agent: *
Disallow: /

resources/views/robotstxt/production.blade.php
User-agent: *
Disallow: